---
name: Build and Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab
    inputs:
      tag:
        description: 'Tag to attach to image'
        required: true
jobs:
  build-and-publish:
    name: Publish container image
    env:
      REGISTRY: quay.io/${{ secrets.QUAY_USER }}
      REPO_NAME: ${{ github.event.repository.name }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BUILDER_PPC64LE_SSH_KEY }}
          name: id_rsa_ppc64le
          known_hosts: unnecessary
          config: |
            Host builder-ppc64le
              HostName ${{ secrets.BUILDER_PPC64LE_SSH_HOST }}
              User root
              IdentityFile ~/.ssh/id_rsa_ppc64le
              StrictHostKeyChecking no

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.11.0
          platforms: linux/amd64
          append: |
            - endpoint: ssh://builder-ppc64le
              platforms: linux/ppc64le

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/ppc64le
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.event.inputs.tag || 'unstable' }}
